import { Property } from "./types";
export const properties: Property[] = [
  {
    label: "438 Capri Court",
    name: "438 Capri Court",
    cleaner: "Wendy",
    service: "Regular Cleaning",
    cost: "375",
    key: "4280",
  },
  {
    label: "921 Tulip Court",
    name: "921 Tulip Court",
    cleaner: "Wendy",
    service: "Light Cleaning",
    cost: "350",
    key: "9832",
  },
  {
    label: "670 West Palm Avenue",
    name: "670 West Palm Avenue",
    cleaner: "Thomas",
    service: "Light Cleaning",
    cost: "350",
    key: "0011",
  },
  {
    label: "Caxambas South Beach Terrace 302",
    name: "Caxambas South Beach Terrace 302",
    cleaner: "Wendy",
    service: "Light Cleaning",
    cost: "300",
    key: "1412",
  },
  {
    label: "775 Hernando Drive",
    name: "775 Hernando Drive",
    cleaner: "Wendy",
    service: "Deep Cleaning",
    cost: "300",
    key: "1111",
  },
  {
    label: "220 Beachcomber Street",
    name: "220 Beachcomber Street",
    cleaner: "Thomas",
    service: "Deep Cleaning",
    cost: "300",
    key: "4292",
  },
  {
    label: "811 Bluebonnet Court",
    name: "811 Bluebonnet Court",
    cleaner: "Thomas",
    service: "Regular Cleaning",
    cost: "300",
    key: "0123",
  },
  {
    label: "807 Fairlawn Court",
    name: "807 Fairlawn Court",
    cleaner: "Thomas",
    service: "Regular Cleaning",
    cost: "250",
    key: "0011",
  },
  {
    label: "Merida 1001",
    name: "Merida 1001",
    cleaner: "Thomas",
    service: "Regular Cleaning",
    cost: "450",
    key: "2151",
  },
  {
    label: "1116 Mulberry Court",
    name: "1116 Mulberry Court",
    cleaner: "Thomas",
    service: "Deep Cleaning",
    cost: "450",
    key: "1411",
  },
];
