import type { NextPage } from "next";
import { useRef } from "react";
import Head from "next/head";
import { AgGridReact } from "ag-grid-react";
import { Record } from "../types";
import ScheduleGrid from "../components/ScheduleGrid";
import ScheduleForm from "../components/ScheduleForm";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const gridRef = useRef<AgGridReact<Record>>(null);

  return (
    <div className={styles.container}>
      <Head>
        <title>Schedule Builder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ScheduleForm gridRef={gridRef} />
        <ScheduleGrid gridRef={gridRef} />
      </main>
      <footer className={styles.footer}>
        <span className={styles.logo}>Copyright 2023</span>
      </footer>
    </div>
  );
};

Home.displayName = "Home";
export default Home;
