import type { NextPage } from "next";
import Head from "next/head";
import ScheduleGrid from "../components/ScheduleGrid";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Schedule Builder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ScheduleGrid />
      </main>
      <footer className={styles.footer}>
        <span className={styles.logo}>Copyright 2023</span>
      </footer>
    </div>
  );
};

export default Home;
